cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f3617062-1fc1-4640-8c3c-6e4e65003cea
description: null
params:
  entity: DEPT_ID
  granularity_sqla: ''
  metric:
    aggregate: AVG
    column:
      column_name: '2004'
      type: INT
    expressionType: SIMPLE
    label: Boys
    optionName: metric_112342
  row_limit: 500000
  select_country: france
  since: ''
  until: ''
  viz_type: country_map
query_context: null
slice_name: Birth in France by department in 2016
uuid: f3e5bce9-4706-422c-9bc0-088b06c32f15
version: 1.0.0
viz_type: country_map
