cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 5ef5734e-8629-49b0-9549-30c2e51bbddd
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: boy
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby:
  - name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__num
  row_limit: 50
  time_range: '100 years ago : now'
  timeseries_limit_metric: sum__num
  viz_type: table
query_context: null
slice_name: Boys
uuid: 802b933d-bf30-4b35-bda6-af63df6241b9
version: 1.0.0
viz_type: table
