cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 97a9b810-0e26-4bfb-a227-d658ce4bb127
description: null
params:
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  datasource: 12__table
  js_columns:
  - color
  js_data_mutator: "data => data.map(d => ({\n    ...d,\n    color: colors.hexToRGB(d.extraProps.color)\n\
    }));"
  js_onclick_href: ''
  js_tooltip: ''
  line_column: path_json
  line_type: json
  line_width: 150
  mapbox_style: mapbox://styles/mapbox/light-v9
  reverse_long_lat: false
  row_limit: 5000
  slice_id: 43
  time_grain_sqla: null
  time_range: ' : '
  viewport:
    altitude: 1.5
    bearing: 0
    height: 1094
    latitude: 37.73671752604488
    longitude: -122.18885402582598
    maxLatitude: 85.05113
    maxPitch: 60
    maxZoom: 20
    minLatitude: -85.05113
    minPitch: 0
    minZoom: 0
    pitch: 0
    width: 669
    zoom: 9.51847667620428
  viz_type: deck_path
query_context: null
slice_name: Deck.gl Path
uuid: 24321618-0d1c-4518-abf4-64f62a5bb6a2
version: 1.0.0
viz_type: deck_path
