cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 5ef5734e-8629-49b0-9549-30c2e51bbddd
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: girl
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '100'
  markup_type: markdown
  metric: sum__num
  rotation: square
  row_limit: 50000
  series: name
  size_from: '10'
  size_to: '70'
  time_range: '100 years ago : now'
  viz_type: word_cloud
query_context: null
slice_name: Girl Name Cloud
uuid: 7585afab-80d0-4564-b923-751d63630eb0
version: 1.0.0
viz_type: word_cloud
