cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 49067df9-0250-49ec-8163-41e7c12e26e3
description: null
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - country_name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  num_period_compare: '10'
  row_limit: 50000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  until: '2014-01-02'
  viz_type: line
query_context: null
slice_name: Growth Rate
uuid: 3ac1359f-764e-4a6a-8d48-62ae813b7ca0
version: 1.0.0
viz_type: line
