cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 49067df9-0250-49ec-8163-41e7c12e26e3
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator:
    - TCA
    - MNP
    - DMA
    - MHL
    - MCO
    - SXM
    - CYM
    - TUV
    - IMY
    - KNA
    - ASM
    - ADO
    - AMA
    - PLW
    expressionType: SIMPLE
    filterOptionName: 2745eae5
    operator: NOT IN
    subject: country_code
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_name
  granularity_sqla: year
  groupby: []
  limit: 0
  markup_type: markdown
  max_bubble_size: '50'
  row_limit: 50000
  series: region
  show_bubbles: true
  since: '2011-01-01'
  size: sum__SP_POP_TOTL
  time_range: '2014-01-01 : 2014-01-02'
  until: '2011-01-02'
  viz_type: bubble
  x: sum__SP_RUR_TOTL_ZS
  y: sum__SP_DYN_LE00_IN
query_context: null
slice_name: Life Expectancy VS Rural %
uuid: e3ede487-9b6a-4f42-91ca-6dc30bce434e
version: 1.0.0
viz_type: bubble
