cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 6e533506-fce6-4f6a-b116-d139df6dbdea
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: github-notifications
    expressionType: SIMPLE
    filterOptionName: filter_7ud3u2eujnw_1pmeehxvw0b
    isExtra: false
    isNew: false
    operator: '!='
    sqlExpression: null
    subject: name
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: ts
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  contributionMode: null
  datasource: 56__table
  groupby:
  - name
  label_colors:
    '0': '#1FA8C9'
    '1': '#454E7C'
    announcements: '#A868B7'
    apache-releases: '#666666'
    beginners: '#666666'
    commits: '#E04355'
    community-feedback: '#EFA1AA'
    contributing: '#8FD3E4'
    cypress-tests: '#FDE380'
    dashboard-filters: '#FCC700'
    dashboard-level-access: '#D1C6BC'
    dashboards: '#3CCCCB'
    design: '#1FA8C9'
    developers: '#9EE5E5'
    embedded-dashboards: '#ACE1C4'
    feature-requests: '#454E7C'
    general: '#3CCCCB'
    github-notifications: '#E04355'
    globalnav_search: '#A1A6BD'
    graduation: '#A1A6BD'
    helm-k8-deployment: '#FEC0A1'
    introductions: '#5AC189'
    jobs: '#FF7F44'
    localization: '#5AC189'
    newsletter: '#FF7F44'
    product_feedback: '#D3B3DA'
    pull-requests: '#A38F79'
    superset-champions: '#FCC700'
    superset_prod_reports: '#A868B7'
    superset_stage_alerts: '#A38F79'
    support: '#8FD3E4'
    visualization_plugins: '#B2B2B2'
  limit: 10
  line_interpolation: linear
  logAxis: false
  markerEnabled: false
  metrics:
  - count
  min_periods: 0
  opacity: 0.7
  order_desc: true
  queryFields:
    groupby: groupby
    metrics: metrics
  rich_tooltip: true
  rolling_periods: 14
  rolling_type: mean
  row_limit: 1000
  show_extra_controls: false
  show_legend: true
  slice_id: 2395
  stack: Stream
  time_grain_sqla: P1D
  truncateYAxis: true
  url_params: {}
  viz_type: echarts_area
  xAxisLabelRotation: 0
  x_axis: ts
  x_axis_showminmax: true
  x_axis_time_format: smart_date
  x_axis_title_margin: auto
  y_axis_bounds:
  - 0
  - null
  y_axis_format: SMART_NUMBER
  zoomable: false
query_context: null
slice_name: Messages per Channel
uuid: b0f11bdf-793f-473f-b7d5-b9265e657896
version: 1.0.0
viz_type: echarts_area
