cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 5ef5734e-8629-49b0-9549-30c2e51bbddd
description: null
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: line
query_context: null
slice_name: Num Births Trend
uuid: 8c38b00d-91e9-440e-a71f-c7ff60362f0e
version: 1.0.0
viz_type: line
