cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 5ef5734e-8629-49b0-9549-30c2e51bbddd
description: null
params:
  compare_lag: '10'
  compare_suffix: o10Y
  granularity_sqla: ds
  groupby: []
  limit: '25'
  markup_type: markdown
  metric:
    aggregate: SUM
    column:
      column_name: num_california
      expression: CASE WHEN state = 'CA' THEN num ELSE 0 END
    expressionType: SIMPLE
    label: SUM(num_california)
  row_limit: 50000
  time_range: '100 years ago : now'
  viz_type: big_number_total
query_context: null
slice_name: Number of California Births
uuid: 481ed255-9ab9-4e8f-aa1c-ac28bf8ce685
version: 1.0.0
viz_type: big_number_total
