cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 5ef5734e-8629-49b0-9549-30c2e51bbddd
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: boy
    expressionType: SIMPLE
    operator: ==
    subject: gender
  compare_lag: '10'
  compare_suffix: o10Y
  comparison_type: values
  granularity_sqla: ds
  groupby:
  - name
  limit: 10
  markup_type: markdown
  metrics:
  - aggregate: SUM
    column:
      column_name: num
      type: BIGINT
    expressionType: SIMPLE
    label: Births
    optionName: metric_11
  row_limit: 50000
  stacked_style: expand
  time_grain_sqla: P1D
  time_range: '100 years ago : now'
  viz_type: area
  x_axis_forma: smart_date
query_context: null
slice_name: Top 10 Boy Name Share
uuid: ce53a734-ad01-4592-b111-f64fa6196709
version: 1.0.0
viz_type: area
