cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 974b7a1c-22ea-49cb-9214-97b7dbd511e0
description: null
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: presetColors
  datasource: 69__table
  groupby:
  - country_name
  label_colors: {}
  metric: count
  number_format: SMART_NUMBER
  queryFields:
    groupby: groupby
    metrics: metrics
  row_limit: 10000
  time_range: No filter
  treemap_ratio: 1.618033988749895
  url_params: {}
  viz_type: treemap_v2
query_context: null
slice_name: Vaccine Candidates per Country
uuid: e2f5a8a7-feb0-4f79-bc6b-01fe55b98b3c
version: 1.0.0
viz_type: treemap_v2
