cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 974b7a1c-22ea-49cb-9214-97b7dbd511e0
description: null
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  columns:
  - product_category
  - clinical_stage
  datasource: 69__table
  linear_color_scheme: schemeYlOrBr
  metric: count
  queryFields:
    groupby: groupby
    metric: metrics
    secondary_metric: metrics
  row_limit: 10000
  slice_id: 3964
  time_range: No filter
  url_params: {}
  viz_type: sunburst_v2
query_context: null
slice_name: Vaccine Candidates per Country & Stage
uuid: f69c556f-15fe-4a82-a8bb-69d5b6954123
version: 1.0.0
viz_type: sunburst_v2
