cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '0'
    expressionType: SIMPLE
    filterOptionName: filter_qzz67uip1ue_jw3rr6tzo3a
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: is_software_dev
  annotation_layers: []
  color_scheme: supersetColors
  datasource: 42__table
  donut: true
  granularity_sqla: time_start
  groupby:
  - job_location_preference
  innerRadius: 44
  label_type: key
  labels_outside: true
  metric: count
  number_format: SMART_NUMBER
  outerRadius: 69
  queryFields:
    groupby: groupby
    metric: metrics
  row_limit: null
  show_labels: true
  show_legend: false
  slice_id: 1370
  time_range: No filter
  url_params: {}
  viz_type: pie
query_context: null
slice_name: Work Location Preference
uuid: e6b09c28-98cf-785f-4caf-320fd4fca802
version: 1.0.0
viz_type: pie
